version: "3"
services:
  notebook:
    build: .
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - discovery.type=single-node
