version: "3"
services:
  jupyter:
    build: .
    environment:
      - JUPYTER_TOKEN=techtalk
    volumes:
      - .:/home/jovyan/work
    ports:
      - 10000:8888
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - discovery.type=single-node
